### ISSUE TITLE
so many problems

### ISSUE THREAD

**Issue by chenyu1990** [gitbitex/gitbitex-new#16]
constantly solving problems, not working

**Comment by greensheng** [comment]
Please describe the specific problem. Thank you.

**Comment by chenyu1990** [comment]
1、[isConnecting 方法找不到](https://github.com/gitbitex/gitbitex-new/blob/a150c5fc7f66c929dba9f83b2a03ac2fcdd28e0d/src/main/java/com/gitbitex/liquidity/CoinbaseTrader.java#L58)
2、coinbase的wss，国内网络无法上，网上找的websocket走proxy的方法都试了，不起作用。
你能加我微信吗？我能有偿找你克隆pro.coinbase.com的trade不？   bmw540i2021

**Comment by greensheng** [comment]
> 

The certificate service used by coinbase Pro seems to be blocked by China's firewall. No proxy tool can connect, and only non Chinese Mainland servers can be used

**Comment by greensheng** [comment]
In addition, [CoinbaseTrader](https://github.com/gitbitex/gitbitex-new/blob/a150c5fc7f66c929dba9f83b2a03ac2fcdd28e0d/src/main/java/com/gitbitex/liquidity/CoinbaseTrader.java) is only used for demonstration, not a real trading robot. Please do not use it in a product environment.
