### ISSUE TITLE
i can run all containers but port 80 not is working

### ISSUE THREAD

**Issue by loveyandex** [gitbitex/gitbitex-new#19]

**Comment by loveyandex** [comment]
http://127.0.0.1/trade/BTC-USDT
not working no server found

**Comment by lovebinance** [comment]
![image](https://user-images.githubusercontent.com/122726018/213913940-01a60a65-651f-4e40-852c-6b910ea25a6b.png)


$ curl localhost 
curl: (7) Failed to connect to localhost port 80 after 2242 ms: Connection refused

**Comment by opadfnezig** [comment]
It doesnt work on windows wsl and shouldn't cause --network=host doesn't. Also, managed to create compose image without using host network, and it still doesn't work on windows (but get errors in different place).

**Comment by loveyandex** [comment]
@greensheng  i studied your project 
it is modeled  very cheap crashable lossable

**Comment by greensheng** [comment]
> @greensheng  i studied your project 
> 
> it is modeled  very cheap crashable lossable

would you tell more details？
