### ISSUE TITLE
error in running with docker

### ISSUE THREAD

**Issue by erfanhemmati** [gitbitex/gitbitex-new#2]
Hello i have done all of docker instructions and commands. but still project does not available in my localhost. is there any instructions/command which i should to do? something like installing java requirements, jdk and ...?

**Comment by erfanhemmati** [comment]
@greensheng

**Comment by greensheng** [comment]
> @greensheng

Execute **docker ps**  and check that all containers are started correctly

-----
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS               NAMES
408396d21712        greensheng/gitbitex        "java -cp /app/res..."   3 minutes ago       Up 3 minutes                            gitbitex
f30f51d6c166        redis                      "docker-entrypoint..."   19 hours ago        Up 19 hours                             redis-server
d2b5d5c30eae        bitnami/kafka:latest       "/opt/bitnami/scri..."   19 hours ago        Up 19 hours                             kafka-server
ed42ae9b2076        bitnami/zookeeper:latest   "/opt/bitnami/scri..."   19 hours ago        Up 19 hours                             zookeeper-server
50c88962a29b        mysql:5.7                  "docker-entrypoint..."   2 days ago          Up 2 days                               mysql

**Comment by erfanhemmati** [comment]
![image](https://user-images.githubusercontent.com/45740840/161956945-a9fd9de0-88fd-4fd4-ba3e-e4d5fb33d983.png)
this is my containers

**Comment by erfanhemmati** [comment]
![image](https://user-images.githubusercontent.com/45740840/161957097-32881f53-e89e-44a3-9b09-f334e80b76f0.png)
but i can not open web interface

**Comment by greensheng** [comment]
> ![image](https://user-images.githubusercontent.com/45740840/161956945-a9fd9de0-88fd-4fd4-ba3e-e4d5fb33d983.png) this is my containers

I didn't see kafka-server. Didn't you start Kafka？

**Comment by erfanhemmati** [comment]
![image](https://user-images.githubusercontent.com/45740840/161960205-5ab59545-c45d-4beb-85a8-9eece84d6559.png)
its here

**Comment by greensheng** [comment]
> ![image](https://user-images.githubusercontent.com/45740840/161960205-5ab59545-c45d-4beb-85a8-9eece84d6559.png) its here

**`docker logs gitbitex`** 
check the log

**Comment by erfanhemmati** [comment]
i am getting a lots of error.
![image](https://user-images.githubusercontent.com/45740840/161961096-9984443e-afd6-4315-9377-1aa6caa2b1b3.png)

**Comment by greensheng** [comment]
> i am getting a lots of error. ![image](https://user-images.githubusercontent.com/45740840/161961096-9984443e-afd6-4315-9377-1aa6caa2b1b3.png)

This is TradeMaker running, you can close it, just for demonstration purposes, keep getting the latest trade from binance, and then place an order on gitbitex.

**Comment by greensheng** [comment]
Did you restart gitbitex after starting kafka-server?

**Comment by erfanhemmati** [comment]
yes i restarted but web interface does not work

**Comment by erfanhemmati** [comment]
> > i am getting a lots of error. ![image](https://user-images.githubusercontent.com/45740840/161961096-9984443e-afd6-4315-9377-1aa6caa2b1b3.png)
> 
> This is TradeMaker running, you can close it, just for demonstration purposes, keep getting the latest trade from binance, and then place an order on gitbitex.

how can i disable it?

**Comment by greensheng** [comment]
> > > i am getting a lots of error. ![image](https://user-images.githubusercontent.com/45740840/161961096-9984443e-afd6-4315-9377-1aa6caa2b1b3.png)
> > 
> > 
> > This is TradeMaker running, you can close it, just for demonstration purposes, keep getting the latest trade from binance, and then place an order on gitbitex.
> 
> how can i disable it?

docker pull greensheng/gitbitex
docker stop gitbitex
docker rm gitbitex
docker run ....

**Comment by erfanhemmati** [comment]
![image](https://user-images.githubusercontent.com/45740840/161966061-ed7b5595-b9f1-4eb6-8957-c556f76d60b8.png)

now i dont have any error but why web interface and services does not working?

**Comment by erfanhemmati** [comment]
change the port can solve the problem?

**Comment by greensheng** [comment]
You seem to be running docker on windows, you need to check your docker network to see if your host can access the docker port

**Comment by erfanhemmati** [comment]
yes iam using docker desktop on windows

**Comment by erfanhemmati** [comment]
is there any maker and taker concept in this project?

**Comment by greensheng** [comment]
> is there any maker and taker concept in this project?

I don't quite understand what you mean.
