### ISSUE TITLE
How to setup the project?

### ISSUE THREAD

**Issue by opadfnezig** [gitbitex/gitbitex-new#20]
The project is great, and I was able to deploy it using guide in readme. But now setup is required, to make all the functions work, and have no idea where to find references. Are they avaliable anywhere?

I don't know how to connect wallets (that's why deposit doesn't work, right?), and don't know where I can get APi references(like, there is api code generation, but does it even work?).

Please, tell me at least it works, can't check demo website for some reasons.

**Comment by greensheng** [comment]
This is only a trading system, without integrated wallet function
