### ISSUE TITLE
The engineListeners, where and how are they used?

### ISSUE THREAD

**Issue by edugrip** [gitbitex/gitbitex-new#25]
Was trying to understand the code ( I am not much experienced in concurrency). in Bootstrap.java how are the engineListeners being used? we are creating a placeholder for them, but we are not assigning anything to those variables, example 
   private final ModifiedObjectWriter modifiedObjectWriter;
    private final EngineSnapshotTaker engineSnapshotTaker;
    private final OrderBookSnapshotTaker orderBookSnapshotTaker;
    private final List<EngineListener> engineListeners;
Top three classes are clearly not being used, engineListener is being use but it appears to be an empty List. Please guide.

**Comment by greensheng** [comment]
These objects are injected through spring ioc 
see：https://www.studytonight.com/spring-framework/spring-configuration-using-java-no-xml
