### ISSUE TITLE
kafka wrapper error

### ISSUE THREAD

**Issue by Freyrecorp1** [gitbitex/gitbitex-new#29]
Hi, I am executing all the steps to launch the project and I find this error in the kafka container

kafka 16:27:27.73 Welcome to the Bitnami kafka container
kafka 16:27:27.73 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka 16:27:27.74 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka 16:27:27.74
kafka 16:27:27.74 INFO ==> ** Starting Kafka setup **
kafka 16:27:27.78 ERROR ==> KRaft requires KAFKA_CFG_NODE_ID to be set for the quorum controller
/opt/bitnami/scripts/libkafka.sh: line 258: KAFKA_CFG_NODE_ID: unbound variable

Has the same thing happened to anyone else? I was reading and in this https://github.com/bitnami/containers/issues/33271 they give an answer but I don't see those variables in the docker-compose.yaml file to try to change it and see if that solves the problem.

**Comment by LHozzan** [comment]
Hi @Freyrecorp1 .

You can copy and use changes from [PR](https://github.com/bitnami/containers/pull/34152/files) and build your own image to bypass the problem until PR will be merged (or processed).

I mean, you can use current Docker image as a start point and place changes to your own image, something like this:

```
FROM bitnami/kafka:3.4.0

# your setup.sh with changes
COPY setup.sh /opt/bitnami/scripts/kafka/setup.sh

# workaround to do new script copy executable
USER root
RUN chmod g+rwX /opt/bitnami
USER 1001
```

Hope that helps.
