### ISSUE TITLE
Liquidity Flow Process

### ISSUE THREAD

**Issue by blockchain-app12** [gitbitex/gitbitex-new#3]
I'm running the docker, match engine flow working fine.
My query was are you using any Liquidity Provider API to stream the Liquidity process functionalities or not ?
If you used the Liquidity provider means, what are steps to follow it in the source code process and if any sql setup need or not for the liquidity flow.
And kindly let me know, this code setup can be suitable for Liquidity streaming or not ?

**Comment by greensheng** [comment]
The code only provides basic functions such as trading and matching, and does not integrate Liquidity Provider. There is a MarketMaker in the fake directory, which synchronizes the trade data of binance, just for system demonstration.
