### ISSUE TITLE
Build Issue - Java Match Engine

### ISSUE THREAD

**Issue by blockchain-app12** [gitbitex/gitbitex-new#33]
I configure the mentioned dependencies as in the README file in my local. After I trying to compile, it throws the error of invalid target.
Kindly let me know, if I was missed any configuarations or dependencies or any other steps to be followed or any other updated source available from your end, let me know. Hereby I attached the error screenshot for your reference.

![image](https://github.com/gitbitex/gitbitex-new/assets/48212011/cbeed5e9-a12c-420c-a0ed-10d142ccef90)

**Comment by greensheng** [comment]
Java version needs to be upgraded to Java 17

**Comment by blockchain-app12** [comment]
I upgraded to java 17 and using the maven version 3.6.0, but now again facing the issue at the compilation stage.

![image](https://github.com/gitbitex/gitbitex-new/assets/48212011/6cbc6118-544c-47d3-9df3-0cc2ce165dd0)

Java and Maven version 

![image](https://github.com/gitbitex/gitbitex-new/assets/48212011/2177a98c-990c-4264-9b2b-587085d451d2)

Kindly provide the support to build the source.

**Comment by hiflorida001** [comment]
I can't pull registry.hub.docker.com/greensheng/gitbitex:demo this image .  so .are you sure your registry has this image

**Comment by puneet166** [comment]
Please use 3.8 version of maven
