### ISSUE TITLE
How to start Kafka?

### ISSUE THREAD

**Issue by munkh-erdene** [gitbitex/gitbitex-new#34]
org.apache.kafka.clients.NetworkClient   : [Consumer clientId=consumer-Trade1-3, groupId=Trade1] Connection to node -1 (localhost/127.0.0.1:19092) could not be established. Broker may not be available.

**Comment by says112** [comment]
![Снимок экрана (553)](https://github.com/gitbitex/gitbitex-new/assets/22127398/0a4429eb-fbb9-4d18-b6ea-b4fe8de8f83b)
I have this problem too. Have you found a solution?

**Comment by says112** [comment]
> org.apache.kafka.clients.NetworkClient: [Consumer clientId=consumer-Trade1-3, groupId=Trade1] Не удалось установить соединение с узлом -1 (localhost/127.0.0.1:19092). Брокер может быть недоступен.

I found the reason why kafko does not start, add in the file: docker-compose.yaml stock: - KAFKA_CFG_NODE_ID=1

**Comment by munkh-erdene** [comment]
Thank you
