### ISSUE TITLE
Orders Page Not Updating With Database

### ISSUE THREAD

**Issue by xbow145** [gitbitex/gitbitex-new#4]
Hello, First of all great work ! one small thing I noticed is the orders pages is not dynamic, when I add another market it indeed creates a new page for it but I cannot see the orders of that new market.
Best Regards !

**Comment by greensheng** [comment]
You mean http://gitbitex.cloud/account/order This page? You need to click the [btc-usdt x] button, and then you can display all products in the drop-down list. This design is not very good. I will redesign it
