### ISSUE TITLE
Docker file missing in the project, manual install how to 

### ISSUE THREAD

**Issue by vandergrafgenerator** [gitbitex/gitbitex-new#6]
I need a manual install how to(no Docker), just like the old Gitbitex had. Maybe the Docker file could do it for me but i could not find it available in the project.

Is the architecture exactly the same as the old Gitbitex? If not, could someone post a chart with the updated one?

As a personal project i want to try to translate Gitbitex to another language, Perl. But i need that info to start! 

Out of curiosity, what is the reasoning for the change from Go to Java?

**Comment by greensheng** [comment]
The project uses **jib**(https://cloud.google.com/java/getting-started/jib?hl=en) for docker image construction, so there is no dockerfile file. You can use the following command to generate an image locally:
```shell
mvn clean compile jib:buildDocker
```

If you don't want to use docker, you can directly build a jar package with the following command, and then start it with Java command
```shell
mvn clean package -Dmaven.test.skip=true
```

Compared with old gitbitex, the architecture has not changed much, but old gitbitex has many problems in the implementation details, such as using a lot of locks (select for update), and the matching thread is not only responsible for matching, but also responsible for snapshots, which will seriously reduce the performance. In new gitbitex, all these have been improved.

About three years ago, I first learned the go language and developed gitbitex with go, but there were many problems with go Kafka at that time, which led to many problems. The main reason for using Java is that I have rich experience in Java.

**Comment by SimonVillage** [comment]
command should be `mvn clean compile jib:dockerBuild`

**Comment by greensheng** [comment]
> SimonHausdorf

Sorry. my mistake, README.md has been updated.
